import {
  BarChart3,
  Bell,
  BookOpen,
  Building2,
  CheckCircle2,
  ClipboardCheck,
  FileText,
  FolderOpen,
  Gavel,
  GraduationCap,
  LayoutDashboard,
  Network,
  Rocket,
  ShieldCheck,
  Sparkles,
  Target,
  UserRound,
  Users,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { Role } from "../types";
import type { ModuleKind, RoleWorkspace, WorkspaceTab } from "../features/workspace/workspace.types";

const baseTabs = {
  profile: {
    id: "profile",
    label: "Profile",
    eyebrow: "Identity",
    description: "Role profile, permissions, scope, and contact context.",
    kind: "profile",
    icon: UserRound,
  },
  onboarding: {
    id: "onboarding",
    label: "Onboarding",
    eyebrow: "Activation",
    description: "Readiness checklist and next setup actions for this role.",
    kind: "onboarding",
    icon: Sparkles,
  },
  audit: {
    id: "audit",
    label: "Audit",
    eyebrow: "Trace",
    description: "Traceable user, workflow, report, and document events.",
    kind: "audit",
    icon: ShieldCheck,
  },
} satisfies Record<string, WorkspaceTab>;

function tab(
  id: string,
  label: string,
  eyebrow: string,
  description: string,
  kind: ModuleKind,
  icon: LucideIcon,
): WorkspaceTab {
  return { id, label, eyebrow, description, kind, icon };
}

export function workspaceFor(role: Role): RoleWorkspace {
  const commonOnboarding: RoleWorkspace["onboarding"] = [
    { label: "Profile verified", status: "done", detail: `${role.organization} scope attached` },
    { label: "Workspace tour", status: "active", detail: "Review the role-specific modules" },
    { label: "First workflow action", status: "pending", detail: "Complete one seeded action for demo" },
  ];

  const workspaces: Record<string, RoleWorkspace> = {
    "pmu-admin": {
      headline: "Programme command center",
      subline: "Control master data, approvals, reports, rollout health, and escalations.",
      commandLabel: "PMU OPS",
      persona: "Central operations owner coordinating institutions, governance, and reporting.",
      profileCompleteness: 92,
      onboarding: commonOnboarding,
      highlights: [
        { label: "Maker-checker", value: "4 queues", detail: "Approvals and escalations" },
        { label: "Rollout", value: "66 schools", detail: "Mapped across hubs" },
        { label: "Evidence", value: "4 packs", detail: "Reports and documents" },
      ],
      nav: [
        tab("overview", "Command", "Live desk", "Programme-wide command center.", "overview", LayoutDashboard),
        tab("map", "Programme Map", "Master data", "Incubators, schools, ownership, and risk.", "institutions", Network),
        tab("pipeline", "Pipeline", "Execution", "Student innovation pipeline and review stages.", "projects", Rocket),
        tab("approvals", "Approval Desk", "Governance", "Maker-checker queue and council actions.", "governance", Gavel),
        tab("reports", "Board Reports", "Exports", "Programme snapshots and official packs.", "reports", BarChart3),
        baseTabs.profile,
        baseTabs.onboarding,
        baseTabs.audit,
      ],
    },
    leadership: {
      headline: "Leadership briefing room",
      subline: "Aggregated health, risks, decisions, outcomes, and official reporting.",
      commandLabel: "APEX",
      persona: "Executive reviewer focused on impact, blockers, and policy decisions.",
      profileCompleteness: 86,
      onboarding: commonOnboarding,
      highlights: [
        { label: "Impact", value: "6,950", detail: "Students in view" },
        { label: "Risks", value: "2 open", detail: "Requires attention" },
        { label: "Decisions", value: "4", detail: "Council items" },
      ],
      nav: [
        tab("briefing", "Briefing", "Executive", "High-level programme health.", "overview", LayoutDashboard),
        tab("impact", "Impact Radar", "Outcomes", "Aggregated schools, students, and projects.", "impact", Target),
        tab("decisions", "Decision Board", "Approvals", "Council approvals and escalations.", "governance", Gavel),
        tab("risk", "Risk Register", "Watchlist", "Institution and project risk signals.", "institutions", Bell),
        tab("reports", "Review Packs", "Reports", "Board-ready reports and utilization snapshots.", "reports", FileText),
        baseTabs.profile,
        baseTabs.audit,
      ],
    },
    secretariat: {
      headline: "Secretariat governance desk",
      subline: "Meetings, minutes, decisions, official records, and action follow-ups.",
      commandLabel: "SECRETARIAT",
      persona: "Governance coordinator maintaining official evidence and committee rhythm.",
      profileCompleteness: 78,
      onboarding: commonOnboarding,
      highlights: [
        { label: "Minutes", value: "v3", detail: "Latest council record" },
        { label: "Actions", value: "4", detail: "Committee tracker" },
        { label: "Documents", value: "2", detail: "Restricted packs" },
      ],
      nav: [
        tab("desk", "Secretariat Desk", "Governance", "Meeting and action command center.", "overview", ClipboardCheck),
        tab("minutes", "Minutes & Decisions", "Records", "Committee records and approvals.", "governance", Gavel),
        tab("documents", "Official Files", "Repository", "Versioned governance documents.", "resources", FolderOpen),
        tab("actions", "Action Tracker", "Follow-up", "Assigned decisions and deadlines.", "projects", CheckCircle2),
        baseTabs.profile,
        baseTabs.onboarding,
        baseTabs.audit,
      ],
    },
    "incubator-admin": {
      headline: "Incubator cluster cockpit",
      subline: "Schools, mentors, workshops, projects, and cluster reports.",
      commandLabel: "CLUSTER",
      persona: "Cluster administrator accountable for mapped schools and mentor operations.",
      profileCompleteness: 81,
      onboarding: commonOnboarding,
      highlights: [
        { label: "Schools", value: "18", detail: "North cluster" },
        { label: "Projects", value: "2", detail: "Visible demo queue" },
        { label: "Reports", value: "1 due", detail: "Quarterly submission" },
      ],
      nav: [
        tab("cluster", "Cluster Home", "Operations", "Cluster health and next actions.", "overview", LayoutDashboard),
        tab("schools", "Mapped Schools", "Network", "Schools under the incubator.", "institutions", Building2),
        tab("reviews", "Project Reviews", "Pipeline", "Student projects and mentor readiness.", "projects", Rocket),
        tab("mentor", "Mentor Bench", "Support", "Mentor assignments and evaluation rubric.", "mentoring", Users),
        tab("reports", "Activity Reports", "Evidence", "Cluster reports and utilization.", "reports", FileText),
        baseTabs.profile,
        baseTabs.onboarding,
      ],
    },
    "school-admin": {
      headline: "School participation hub",
      subline: "Students, teachers, curriculum calendar, reports, and participation evidence.",
      commandLabel: "SCHOOL",
      persona: "School administrator managing local programme participation and reporting.",
      profileCompleteness: 74,
      onboarding: commonOnboarding,
      highlights: [
        { label: "Students", value: "420", detail: "Riverdale scope" },
        { label: "Projects", value: "2", detail: "School pipeline" },
        { label: "Reports", value: "1", detail: "Weekly register" },
      ],
      nav: [
        tab("school", "School Home", "Operations", "Local school dashboard.", "overview", LayoutDashboard),
        tab("students", "Student Roster", "People", "Student and teacher participation.", "students", GraduationCap),
        tab("learning", "Learning Plan", "Curriculum", "Curriculum and resource schedule.", "learning", BookOpen),
        tab("studio", "Project Studio", "Projects", "School project tracking.", "projects", Rocket),
        tab("reports", "School Reports", "Evidence", "Participation and submission reports.", "reports", BarChart3),
        baseTabs.profile,
        baseTabs.onboarding,
      ],
    },
    teacher: {
      headline: "Teacher champion studio",
      subline: "Cohorts, curriculum, submissions, project support, and mentor notes.",
      commandLabel: "CHAMPION",
      persona: "Teacher champion guiding learners through curriculum and project delivery.",
      profileCompleteness: 69,
      onboarding: commonOnboarding,
      highlights: [
        { label: "Cohort", value: "16", detail: "Teachers in school" },
        { label: "Projects", value: "2", detail: "Classroom queue" },
        { label: "Feedback", value: "2", detail: "Mentor touchpoints" },
      ],
      nav: [
        tab("home", "Champion Home", "Today", "Classroom workbench.", "overview", LayoutDashboard),
        tab("cohort", "Cohort", "Students", "Student progress and participation.", "students", Users),
        tab("curriculum", "Curriculum", "Learning", "Resources and learning plan.", "learning", BookOpen),
        tab("projects", "Project Studio", "Build", "Project submissions and evidence.", "projects", Rocket),
        tab("feedback", "Mentor Notes", "Review", "Mentor review and next steps.", "mentoring", ClipboardCheck),
        baseTabs.profile,
        baseTabs.onboarding,
      ],
    },
    student: {
      headline: "Student innovation studio",
      subline: "Your learning plan, project evidence, mentor feedback, and showcase readiness.",
      commandLabel: "STUDENT",
      persona: "Learner building a project, following curriculum, and collecting evidence.",
      profileCompleteness: 64,
      onboarding: [
        { label: "Student profile created", status: "done", detail: "Riverdale Public School linked" },
        { label: "Learning pack opened", status: "active", detail: "Innovation Curriculum Pack assigned" },
        { label: "Evidence upload", status: "pending", detail: "Prototype proof due before mentor review" },
      ],
      highlights: [
        { label: "My project", value: "86", detail: "Solar monitor score" },
        { label: "Learning", value: "1 pack", detail: "Assigned curriculum" },
        { label: "Next", value: "Mentor", detail: "Feedback due" },
      ],
      nav: [
        tab("studio", "My Studio", "Today", "Personal progress and next action.", "overview", Sparkles),
        tab("learning", "Learning", "Curriculum", "Assigned learning resources.", "learning", BookOpen),
        tab("project", "My Project", "Build", "Your project, score, mentor, and evidence.", "projects", Rocket),
        tab("feedback", "Mentor Feedback", "Review", "Mentor comments and review queue.", "mentoring", ClipboardCheck),
        tab("evidence", "Evidence", "Documents", "Uploads and project artefacts.", "resources", FolderOpen),
        baseTabs.profile,
        baseTabs.onboarding,
      ],
    },
    mentor: {
      headline: "Mentor review console",
      subline: "Assigned projects, rubrics, student feedback, and review history.",
      commandLabel: "MENTOR",
      persona: "Expert reviewer helping teams improve and prepare for showcase.",
      profileCompleteness: 71,
      onboarding: commonOnboarding,
      highlights: [
        { label: "Reviews", value: "2", detail: "Assigned projects" },
        { label: "Rubric", value: "v1.4", detail: "Evaluation pack" },
        { label: "Risk", value: "1", detail: "Needs support" },
      ],
      nav: [
        tab("queue", "Review Queue", "Mentor", "Assigned project reviews.", "mentoring", ClipboardCheck),
        tab("projects", "Projects", "Pipeline", "Projects assigned to you.", "projects", Rocket),
        tab("rubric", "Rubric", "Resources", "Review rubric and evidence guides.", "resources", BookOpen),
        tab("profile", "Profile", "Identity", "Mentor profile and expertise.", "profile", UserRound),
        baseTabs.onboarding,
      ],
    },
    "funding-partner": {
      headline: "Funding partner view",
      subline: "Funded cohorts, utilization reports, project highlights, and evidence packs.",
      commandLabel: "CSR",
      persona: "Funding partner monitoring funded cohorts and utilization evidence.",
      profileCompleteness: 83,
      onboarding: commonOnboarding,
      highlights: [
        { label: "Coverage", value: "2 hubs", detail: "Funded cohorts" },
        { label: "Utilization", value: "89%", detail: "CSR statement" },
        { label: "Projects", value: "4", detail: "Visible highlights" },
      ],
      nav: [
        tab("funding", "Funding Home", "Partner", "Funded cohort overview.", "overview", LayoutDashboard),
        tab("cohorts", "Funded Cohorts", "Coverage", "Institutions in funded scope.", "institutions", Building2),
        tab("impact", "Impact Stories", "Projects", "Project highlights and outcomes.", "impact", Target),
        tab("utilization", "Utilization", "Reports", "Funding and utilization reports.", "funding", BarChart3),
        tab("documents", "Evidence Packs", "Files", "Partner-visible documents.", "resources", FolderOpen),
        baseTabs.profile,
        baseTabs.onboarding,
      ],
    },
  };

  return workspaces[role.id] ?? workspaces["pmu-admin"];
}
