import type { DemoRole, Institution, Project } from "./types.js";

export const roles: DemoRole[] = [
  {
    id: "pmu-admin",
    label: "PMU Admin",
    short_label: "PMU",
    name: "Aarav Mehta",
    organization: "State PMU",
    scope: "Programme-wide operational access",
    accent: "teal",
    permissions: ["manage", "approve", "reports", "documents", "audit"],
  },
  {
    id: "leadership",
    label: "Apex Leadership",
    short_label: "Lead",
    name: "Dr. Meera Iyer",
    organization: "Apex Council",
    scope: "Aggregated impact and governance view",
    accent: "blue",
    permissions: ["approve", "reports", "audit"],
  },
  {
    id: "secretariat",
    label: "Secretariat",
    short_label: "Sec",
    name: "Kabir Rao",
    organization: "Central Secretariat",
    scope: "Committee records and governance actions",
    accent: "amber",
    permissions: ["manage", "approve", "documents", "audit"],
  },
  {
    id: "incubator-admin",
    label: "Incubator Admin",
    short_label: "Inc",
    name: "Nisha Kapoor",
    organization: "North Innovation Hub",
    scope: "North cluster schools",
    accent: "violet",
    permissions: ["manage", "reports", "documents"],
  },
  {
    id: "school-admin",
    label: "School Admin",
    short_label: "School",
    name: "Principal Farah Khan",
    organization: "Riverdale Public School",
    scope: "Own school and mapped students",
    accent: "green",
    permissions: ["manage", "reports", "documents"],
  },
  {
    id: "teacher",
    label: "Teacher Champion",
    short_label: "Teacher",
    name: "Rahul Sen",
    organization: "Riverdale Public School",
    scope: "Assigned students and projects",
    accent: "orange",
    permissions: ["manage", "documents"],
  },
  {
    id: "student",
    label: "Student",
    short_label: "Student",
    name: "Ananya Das",
    organization: "Riverdale Public School",
    scope: "Own learning and innovation project",
    accent: "rose",
    permissions: ["documents"],
  },
  {
    id: "mentor",
    label: "Mentor / Expert",
    short_label: "Mentor",
    name: "Vikram Shah",
    organization: "Mentor Network",
    scope: "Assigned project reviews",
    accent: "cyan",
    permissions: ["manage", "documents"],
  },
  {
    id: "funding-partner",
    label: "Funding Partner",
    short_label: "CSR",
    name: "Leena Thomas",
    organization: "FutureWorks CSR",
    scope: "Funded cohorts and utilization reports",
    accent: "slate",
    permissions: ["reports", "documents"],
  },
];

export const institutions: Institution[] = [
  {
    id: "north-hub",
    type: "Incubator",
    name: "North Innovation Hub",
    region: "North",
    owner: "Nisha Kapoor",
    schools: 18,
    students: 1860,
    teachers: 72,
    projects: 143,
    health: 92,
    report_status: "Submitted",
    risk: "Low",
  },
  {
    id: "riverdale",
    type: "School",
    name: "Riverdale Public School",
    region: "North",
    owner: "Principal Farah Khan",
    schools: 1,
    students: 420,
    teachers: 16,
    projects: 34,
    health: 88,
    report_status: "Submitted",
    risk: "Low",
  },
  {
    id: "east-hub",
    type: "Incubator",
    name: "East Makers Lab",
    region: "East",
    owner: "Sonal Jain",
    schools: 14,
    students: 1280,
    teachers: 54,
    projects: 96,
    health: 76,
    report_status: "In review",
    risk: "Medium",
  },
  {
    id: "hillcrest",
    type: "School",
    name: "Hillcrest STEM School",
    region: "East",
    owner: "Arjun Menon",
    schools: 1,
    students: 310,
    teachers: 12,
    projects: 21,
    health: 69,
    report_status: "Due",
    risk: "Medium",
  },
  {
    id: "south-hub",
    type: "Incubator",
    name: "South Tech Garage",
    region: "South",
    owner: "Divya Nair",
    schools: 20,
    students: 2140,
    teachers: 81,
    projects: 162,
    health: 84,
    report_status: "Submitted",
    risk: "Low",
  },
  {
    id: "west-hub",
    type: "Incubator",
    name: "West Catalyst Centre",
    region: "West",
    owner: "Harsh Patel",
    schools: 12,
    students: 940,
    teachers: 39,
    projects: 58,
    health: 61,
    report_status: "Escalated",
    risk: "High",
  },
];

export const projects: Project[] = [
  {
    id: "p-101",
    title: "Solar Classroom Monitor",
    school: "Riverdale Public School",
    incubator: "North Innovation Hub",
    owner: "Ananya Das",
    mentor: "Vikram Shah",
    stage: "Prototype",
    score: 86,
    status: "On track",
    risk: "Low",
    next_action: "Mentor feedback due",
    due_date: "2026-06-18",
  },
  {
    id: "p-102",
    title: "Low-cost Water Quality Kit",
    school: "Hillcrest STEM School",
    incubator: "East Makers Lab",
    owner: "Team Aqua",
    mentor: "Rhea Mukherjee",
    stage: "Review",
    score: 74,
    status: "Needs support",
    risk: "Medium",
    next_action: "Upload test evidence",
    due_date: "2026-06-16",
  },
  {
    id: "p-103",
    title: "Assistive Reading Board",
    school: "Garden Valley School",
    incubator: "South Tech Garage",
    owner: "Team Access",
    mentor: "Vikram Shah",
    stage: "Demo ready",
    score: 91,
    status: "On track",
    risk: "Low",
    next_action: "Prepare showcase pitch",
    due_date: "2026-06-20",
  },
  {
    id: "p-104",
    title: "Smart Compost Bin",
    school: "Westview Model School",
    incubator: "West Catalyst Centre",
    owner: "EcoLab Group",
    mentor: "Karan Bose",
    stage: "Blocked",
    score: 48,
    status: "Escalated",
    risk: "High",
    next_action: "Resolve parts procurement",
    due_date: "2026-06-13",
  },
  {
    id: "p-105",
    title: "Campus Energy Audit App",
    school: "Riverdale Public School",
    incubator: "North Innovation Hub",
    owner: "Team WattWise",
    mentor: "Rhea Mukherjee",
    stage: "Concept",
    score: 67,
    status: "Needs support",
    risk: "Medium",
    next_action: "Finalize measurement plan",
    due_date: "2026-06-19",
  },
];

export const approvals = [
  {
    id: "a-201",
    title: "North cluster quarterly report",
    module: "Reports",
    owner: "Nisha Kapoor",
    requester_role: "Incubator Admin",
    status: "Pending PMU approval",
    priority: "High",
    age: "2d",
  },
  {
    id: "a-202",
    title: "Committee minutes v3",
    module: "Governance",
    owner: "Kabir Rao",
    requester_role: "Secretariat",
    status: "Council review",
    priority: "Medium",
    age: "4h",
  },
  {
    id: "a-203",
    title: "School onboarding batch 04",
    module: "Institutions",
    owner: "Aarav Mehta",
    requester_role: "PMU Admin",
    status: "Maker-checker",
    priority: "Medium",
    age: "1d",
  },
  {
    id: "a-204",
    title: "West hub exception request",
    module: "Risk",
    owner: "Harsh Patel",
    requester_role: "Incubator Admin",
    status: "Escalated",
    priority: "Critical",
    age: "5d",
  },
];

export const resources = [
  {
    id: "r-301",
    title: "Innovation Curriculum Pack",
    type: "Curriculum",
    version: "v2.1",
    audience: "Teachers and students",
    owner: "Programme Team",
    access: "School scope",
    updated_at: "2026-06-09",
  },
  {
    id: "r-302",
    title: "Mentor Review Rubric",
    type: "Evaluation",
    version: "v1.4",
    audience: "Mentors",
    owner: "M&E Team",
    access: "Assigned reviewers",
    updated_at: "2026-06-07",
  },
  {
    id: "r-303",
    title: "Governing Council Minutes",
    type: "Governance",
    version: "v3.0",
    audience: "Committee members",
    owner: "Secretariat",
    access: "Restricted",
    updated_at: "2026-06-10",
  },
  {
    id: "r-304",
    title: "CSR Utilization Statement",
    type: "Funding",
    version: "v1.2",
    audience: "Funding partners",
    owner: "Finance PMU",
    access: "Partner scope",
    updated_at: "2026-06-08",
  },
];

export const reports = [
  {
    id: "rep-401",
    name: "Monthly Programme Snapshot",
    cadence: "Monthly",
    owner: "PMU",
    status: "Ready",
    coverage: 94,
  },
  {
    id: "rep-402",
    name: "School Participation Register",
    cadence: "Weekly",
    owner: "Schools",
    status: "3 due",
    coverage: 82,
  },
  {
    id: "rep-403",
    name: "Project Review Pack",
    cadence: "Fortnightly",
    owner: "Mentors",
    status: "In review",
    coverage: 76,
  },
  {
    id: "rep-404",
    name: "CSR Funding Utilization",
    cadence: "Quarterly",
    owner: "Funding",
    status: "Ready",
    coverage: 89,
  },
];

export const auditEvents = [
  {
    actor: "Aarav Mehta",
    role: "PMU Admin",
    event: "approved school mapping update",
    module: "Institutions",
  },
  {
    actor: "Kabir Rao",
    role: "Secretariat",
    event: "uploaded committee minutes v3",
    module: "Governance",
  },
  {
    actor: "Rahul Sen",
    role: "Teacher Champion",
    event: "submitted prototype evidence",
    module: "Projects",
  },
  {
    actor: "Nisha Kapoor",
    role: "Incubator Admin",
    event: "sent quarterly report for review",
    module: "Reports",
  },
  {
    actor: "Vikram Shah",
    role: "Mentor",
    event: "completed two project reviews",
    module: "Projects",
  },
];
